[build]
  publish = "."
  command = "pip install -r requirements.txt -t .netlify/python && pip install ./packages/autosar-0.5.5-py3-none-any.whl -t .netlify/python"

[build.environment]
  PYTHON_VERSION = "3.12"

[functions]
  directory = "netlify/functions"
  python_runtime = "python3.12"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200